In [2]:
import sys
import os
from pymatgen.core import Structure
from pymatgen.io.cif import CifWriter
from pymatgen.io.xcrysden import XSF
import numpy as np
import matplotlib.pyplot as plt
import glob
import csv

Structure Summary
Lattice
    abc : 10.25457932 10.25457932 5.579966
 angles : 90.0 90.0 119.99999561000001
 volume : 508.1569866513563
      A : 10.25457932 0.0 6.279118870420321e-16
      B : -5.12728897955915 8.880726589095227 6.279118870420321e-16
      C : 0.0 0.0 5.579966
PeriodicSite: Si (2.5169, 0.0697, 1.9693) [0.2494, 0.0078, 0.3529]
PeriodicSite: Si (9.0230, 2.0788, 3.6835) [0.9969, 0.2341, 0.6601]
PeriodicSite: Si (1.2477, 2.3884, 0.0547) [0.2561, 0.2689, 0.0098]
PeriodicSite: Si (-0.0089, 4.6272, 1.7735) [0.2597, 0.5210, 0.3178]
PeriodicSite: Si (6.3421, 6.5158, 3.6792) [0.9853, 0.7337, 0.6594]
PeriodicSite: Si (-1.3528, 6.6830, 0.0689) [0.2443, 0.7525, 0.0123]
PeriodicSite: Si (7.6080, 0.1529, 1.8269) [0.7505, 0.0172, 0.3274]
PeriodicSite: Si (3.6735, 2.1647, 3.7439) [0.4801, 0.2438, 0.6710]
PeriodicSite: Si (6.3699, 2.2538, 0.1200) [0.7481, 0.2538, 0.0215]
PeriodicSite: Si (5.0129, 4.3602, 1.7934) [0.7343, 0.4910, 0.3214]
PeriodicSite: Si (1.2557, 6.8375, 3.7243) [0.5074

[ 1.732559   -0.8794818  -2.79916601] O 4.924907560464939
[ 2.49528418 -2.44333504 -0.90586301] O 3.8187188738119846
[-1.6519568  -0.77970293  0.87703997] O 4.3924760123221365
[-0.97280856 -3.36831546  0.93562002] O 5.006649607103442
[ 0.97324488 -5.57085226  0.79064999] O 5.965572875397207
[-0.11436316 -4.52051461  1.79344298] Si 5.293823204526988
[ 0.06513433 -1.87962985 -0.84890701] O 4.2134881281961
[-1.14004852 -2.29188978 -0.07611899] Si 4.809801202984887
[ 1.21481743 -2.36495232 -1.900783  ] Si 4.754025386791382
[ 1.732559   -0.8794818   2.78079999] O 1.4746560547952252
[ 2.49528418 -2.44333504  4.67410299] O 3.692105436189379
[ 0.06513433 -1.87962985  4.73105899] O 4.175899420183113
[ 1.06298829 -3.56562203  2.66215602] O 3.9761108125918088
[-1.14004852 -2.29188978  5.50384701] Si 5.607415009741705
[ 1.21481743 -2.36495232  3.679183  ] Si 3.2475447115122513
[0.8472694  3.49340946 0.80337399] O 3.9835654584669125
[1.57799406 0.84388971 0.82270098] O 1.6720151966899321
[-0.008901